web:
  restart: always
  build: .
  expose:
    - "8000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/radio/static
  env_file: radio/configs/docker/env
  command: radio/configs/docker/docker-entrypoint.sh

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - dbstorage
  ports:
    - "5432:5432"

dbstorage:
  image: postgres:latest
  volumes:
    - data:/var/lib/postgresql